'use client';
import { useState, useEffect } from 'react';
import NavBar from '@components/all/NavBar/NavBar';
import HistoryHead from '@components/reservation-list/HistoryHead';
import HistoryInProgressItem from '@components/reservation-list/HistoryInProgressItem';
import HistoryEndItem from '@components/reservation-list/HistoryEndItem';
import {
  HistoryInProgressItemProps,
  HistoryEndItemProps,
  ReservationItemProps,
} from 'types/reservation-list/ReservationListPageTypes';
import NoneResultUI from '@components/all/NoneResultUI/NoneResultUI';
import NoneArrowHeader from '@components/all/NoneArrowHeader';
import Modal from '@components/all/Modal';
import useModal from '@store/modalStore';
import { postUserReservation } from '@apis/payment/before/postReservation';
import { useGetReservationList } from '@apis/reservation-list/getUserReservationList';

const MockReservationData: ReservationItemProps[] = [
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName:
      '스카이락 볼링장 스카이락 볼링장 스카이락 볼링장 스카이락 볼링장 스카이락 볼링장',
    clubAddress:
      '서울 서대문구 신촌로 73 케이스빌딩 4층 서울 서대문구 신촌로 73 케이스빌딩 서울 서대문구 신촌로 73 케이스빌딩 ',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 2,
    teenagerCount: 1,
    kidsCount: 0,
    date: '2024-07-24',
    startTime: '10:00',
    endTime: '12:00',
    price: 150,
    status: 'CONFIRMED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 3,
    teenagerCount: 0,
    kidsCount: 2,
    date: '2024-08-24',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'TBC',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
  {
    adultCount: 1,
    teenagerCount: 1,
    kidsCount: 1,
    date: '2024-08-25',
    startTime: '14:00',
    endTime: '16:00',
    price: 250,
    status: 'DECLINED',
    memberId: null,
    clubId: null,
    type: null,
    businessHours: null,
    clubName: '스카이락 볼링장',
    clubAddress: '서울 서대문구 신촌로 73 케이스빌딩 4층',
    reservationId: null,
  },
];
export default function Page() {
  const [historyHeadState, setHistoryHeadState] = useState<
    '전체' | '진행중' | '종료된'
  >('전체');
  const [reservationList, setReservationList] = useState<
    ReservationItemProps[]
  >([]);

  const inProgressReservationList = reservationList.filter(
    (reservationItem) =>
      reservationItem.status === 'CONFIRMED' || reservationItem.status === 'TBC'
  );

  const endReservationList = reservationList.filter(
    (reservationItem) =>
      reservationItem.status !== 'CONFIRMED' && reservationItem.status !== 'TBC'
  );

  const setSelectedIsModalOpen = useModal(
    (state) => state.setSelectedIsModalOpen
  );

  const { data } = useGetReservationList();

  useEffect(() => {
    return () => {
      setSelectedIsModalOpen(false);
    };
  }, []);

  useEffect(() => {
    setReservationList(MockReservationData);
  }, []);

  return (
    <div className="flex flex-col h-full pb-[54px] items-center">
      <NoneArrowHeader title="예약내역" />
      <HistoryHead
        totalCount={reservationList.length}
        inProgressCount={inProgressReservationList.length}
        completedCount={endReservationList.length}
        historyHeadState={historyHeadState}
        handleHeadState={setHistoryHeadState}
      />
      {historyHeadState === '전체' && reservationList.length === 0 && (
        <main className="w-full h-full flex flex-col top-[117px] justify-center items-center gap-y-[10px] overflow-y-scroll">
          <NoneResultUI
            message="예약 내역이 없어요"
            subMessage="마음에 드는 장소를 찾아 예약해보세요!"
          />
        </main>
      )}

      {historyHeadState === '전체' && reservationList.length !== 0 && (
        <main className="w-full max-h-reservationListMain pt-5 pb-10 flex flex-col top-[117px] absolute justify-start items-center gap-y-[10px] overflow-y-scroll">
          {reservationList.map((reservationItem, index) =>
            reservationItem.status === 'TBC' ||
            reservationItem.status === 'CONFIRMED' ? (
              <HistoryInProgressItem
                key={index}
                clubName={reservationItem.clubName}
                clubAddress={reservationItem.clubAddress}
                eventDate={reservationItem.date}
                eventStartTime={reservationItem.startTime}
                eventEndTime={reservationItem.endTime}
                adultCount={reservationItem.adultCount}
                teenagerCount={reservationItem.teenagerCount}
                kidsCount={reservationItem.kidsCount}
                reservationStatus={reservationItem.status}
                reservationId={index}
              />
            ) : (
              <HistoryEndItem
                key={index}
                clubName={reservationItem.clubName}
                clubAddress={reservationItem.clubAddress}
                eventDate={reservationItem.date}
                eventStartTime={reservationItem.startTime}
                eventEndTime={reservationItem.endTime}
                adultCount={reservationItem.adultCount}
                teenagerCount={reservationItem.teenagerCount}
                kidsCount={reservationItem.kidsCount}
                reservationStatus={reservationItem.status}
                reservationId={index} //일단 백엔드에서 추후에 예약과 review id를 줌
                reviewId={index}
              />
            )
          )}
        </main>
      )}

      {historyHeadState === '진행중' &&
        inProgressReservationList.length === 0 && (
          <main className="w-full h-full flex flex-col top-[117px] justify-center items-center gap-y-[10px] overflow-y-scroll">
            <NoneResultUI
              message="예약 내역이 없어요"
              subMessage="마음에 드는 장소를 찾아 예약해보세요!"
            />
          </main>
        )}

      {historyHeadState === '진행중' &&
        inProgressReservationList.length !== 0 && (
          <main className="w-full max-h-reservationListMain pt-5 pb-10 flex flex-col top-[117px] absolute justify-start items-center gap-y-[10px] overflow-y-scroll">
            {inProgressReservationList.map((data, index) => (
              <HistoryInProgressItem
                key={index}
                clubName={data.clubName}
                clubAddress={data.clubAddress}
                eventDate={data.date}
                eventStartTime={data.startTime}
                eventEndTime={data.endTime}
                adultCount={data.adultCount}
                teenagerCount={data.teenagerCount}
                kidsCount={data.kidsCount}
                reservationStatus={data.status}
                reservationId={index}
              />
            ))}
          </main>
        )}

      {historyHeadState === '종료된' && endReservationList.length === 0 && (
        <main className="w-full h-full flex flex-col top-[117px] justify-center items-center gap-y-[10px] overflow-y-scroll">
          <NoneResultUI
            message="예약 내역이 없어요"
            subMessage="마음에 드는 장소를 찾아 예약해보세요!"
          />
        </main>
      )}

      {historyHeadState === '종료된' && endReservationList.length !== 0 && (
        <main className="w-full max-h-reservationListMain pt-5 pb-10 flex flex-col top-[117px] absolute justify-start items-center gap-y-[10px] overflow-y-scroll">
          {endReservationList.map((data, index) => (
            <HistoryEndItem
              key={index}
              clubName={data.clubName}
              clubAddress={data.clubAddress}
              eventDate={data.date}
              eventStartTime={data.startTime}
              eventEndTime={data.endTime}
              adultCount={data.adultCount}
              teenagerCount={data.teenagerCount}
              kidsCount={data.kidsCount}
              reservationStatus={data.status}
              reservationId={index}
              reviewId={index}
            />
          ))}
        </main>
      )}
      <Modal
        size="lg"
        button1Content="이전으로"
        button2Content="취소하기"
        title="예약을 취소하시겠습니까?"
        subTitle="예약 취소 시 수수료가 발생할 수 있습니다"
      />
      {/* <NavBar /> */}
    </div>
  );
}
